### ISSUE TITLE
Retrain models using latest wikepdia data

### ISSUE THREAD

**Issue by mouthgalya** [facebookresearch/GENRE#12]
Hi,
Some of the users might have asked this question already. What's the script to be used for retraining the model on the latest 2021 Wikepdia data ?

**Comment by nicola-decao** [comment]
Hi,
We are preparing to release the code to convert a Wikipedia dump to the training format required for GENRE. I can see this happening in 3/4 weeks.

If you already have a preprocessed Wikipedia dump you can just use it to generate `train.source, `train.target`, `dev.source` and `dev.target` files and then call [scripts/preprocess_fairseq.sh](https://github.com/facebookresearch/GENRE/blob/main/scripts/preprocess_fairseq.sh) and [scripts/train.sh](https://github.com/facebookresearch/GENRE/blob/main/scripts/train.sh) to binarize the data and train.

**Comment by mouthgalya** [comment]
Thanks a lot for the quick reply. I am pretty new to the entity linking and disambiguation. Some basic questions below
1.) What's the right location to get the latest Wikepedia data dump and what are the right type of files to download? Any pointers here would be helpful.
2.) What's the preprocessing you are referring to? Is it converting it into KILT data format. If yes, what are the steps to do that?

**Comment by vnik18** [comment]
Can you please provide samples of the `train.source` and `train.target` files? Thank you!

**Comment by nicola-decao** [comment]
@mouthgalya @vnik18 I released the training dataset. Unfortunately, I do not have the code to convert a Wikipedia dump in the desired format but it should not take you a lot of time to code it (since it just requires converting HTML into markdown and some regexp to clean it/ argument it). https://github.com/facebookresearch/GENRE/commit/3dcca285d04a4b0cc4e93a0065434417974bd4da
