### ISSUE TITLE
Settings for evaluation

### ISSUE THREAD

**Issue by hideaki-j** [facebookresearch/GENRE#30]
Hi! Thank you for your great work.

I have two questions related to evaluation.
1. Could you share the setting details when you evaluate GENRE? Do you have any plan to share the evaluation environment (including middleware for GERBIL, which is used to communicate with its platform)?
2. Is there a setting to allow the GPU to be used for inference? (By default, GPU is not used for inference, right?)

**Details:**
To confirm my GENRE settings are the best-performed ones, I have been trying to reproduce the end-to-end entity linking results, but could not.

I followed [this example](https://github.com/facebookresearch/GENRE/tree/main/examples_genre#example-end-to-end-entity-linking), and evaluated using the [GERBIL platform](http://gerbil.aksw.org/gerbil/config). 

To extract the spans, I used [_get_entity_spans](https://github.com/facebookresearch/GENRE/issues/20#issuecomment-814000709) function.

I used KORE50 datasets for evaluation, but could not get good results. (for results, see [here](http://gerbil.aksw.org/gerbil/experiment?id=202105200000))

Maybe there is a problem with my GENRE settings, pre-processing or post-processing. I would appreciate it if you could give me more details.

**Comment by nicola-decao** [comment]
Hi! 

If you can run the example, there is no problem with your GENRE setting AFAIK. The problem is in the setting:

1. as you can see from the examples we have a setting where we use a `mention_trie` and a `mention_to_candidates_dict`. I used them as not empty for the experiments in the paper. In particular, I used the entity universe from https://github.com/dalab/end2end_neural_el and the same from the mapping from mention to candidates.  I also did some filerting (e.g., since the task is named entity linking and not entity linking in general, I removed all mentions that do not start with a capital letter).
2. I did not use the function `get_entity_spans` for evaluating with GERBIL. That function was added in the repo afterwards to demonstrate how to get predictions using GENRE. For instance, that function does not handle splitting the input into chunks when is too long which is needed for evaluating properly (since BART can handle at most 1024 tokens). I also had to modify some code (from https://github.com/dalab/end2end_neural_el and the GERBIL repository for enabling having the middleware and unfortunately we cannot release that code).

I hope this is helfpul.

**Comment by hideaki-j** [comment]
Thank you very much for your detailed answer. It is very clear.

Could I also ask about the question 2 above: Is there any setting to allow the GPU to be used for inference? (By default, GPU is not used for inference, right?)

**Comment by nicola-decao** [comment]
As for any other model in pytorch you can do `.cuda`

**Comment by hideaki-j** [comment]
Thanks!

**Comment by hasibi** [comment]
Dear Nicola,

Thank you for your response and interesting work. We are struggling to reproduce your results. Can you please share your evaluation code and also all the changes that affect the results, but have been included in this repository (e.g., the changes you mentioned in [your response](https://github.com/facebookresearch/GENRE/issues/30#issuecomment-846373514))?

I guess there should not be IP/copyright issues to share your evaluation code and GERBIL middleware, right?
