### ISSUE TITLE
Problem in reproducing entity linking results

### ISSUE THREAD

**Issue by Wenyueh** [facebookresearch/GENRE#37]
Hello, thank you for the very interesting idea and work!

However, I have a few questions about the reproduction of the results of end-to-end entity linking, as I failed to obtain comparable results:
1. Could you share the details about the functions used in generating the results and corresponding inputs/settings?
2. Could you share the entity universe and mention-to-candidate mappings from the paper [End-to-End Neural Entity Linking](https://github.com/dalab/end2end_neural_el), as mentioned in issue #30? Could you also detail how these are used in the function [get_prefix_allowed_token_fn](https://github.com/facebookresearch/GENRE/blob/3dcca285d04a4b0cc4e93a0065434417974bd4da/genre/entity_linking.py#L43)? (i.e. what is used for mention_trie and and what is used for mention-to-candidate mapping trie)
3. If it is possible, could you please share the code that runs the experiments on the GERBIL platform?

Thank you very much!

Below are the details about how I ran my experiments:

**Details**:
I used the model fairseq_e2e_entity_linking_aidayago and evaluated it on the GERBIL platform. I preprocessed the sentences using the function [get_entity_spans_pre_processing](https://github.com/facebookresearch/GENRE/blob/3dcca285d04a4b0cc4e93a0065434417974bd4da/genre/utils.py#L97), generated predictions using [model.sample](https://github.com/facebookresearch/GENRE/blob/63e5f98677f84bd0bc918930cad90e6a683f6467/genre/fairseq_model.py#L22), post-preprocessed the predictions using [get_entity_spans_post_processing](https://github.com/facebookresearch/GENRE/blob/63e5f98677f84bd0bc918930cad90e6a683f6467/genre/utils.py#L111) and generated the entity triples by [get_entity_spans_finalize](https://github.com/facebookresearch/GENRE/blob/63e5f98677f84bd0bc918930cad90e6a683f6467/genre/utils.py#L192).  The [get_prefix_allowed_token_fn](https://github.com/facebookresearch/GENRE/blob/3dcca285d04a4b0cc4e93a0065434417974bd4da/genre/entity_linking.py#L43) used in model.sample takes None for mention_trie and mention_to_candidates_dict. 

I evaluated the results on **KORE50** and **Derczynski**. 
The result for KORE50 is: 
micro F1: 42.11
micro precision: 37.78
micro recall: 47.55
macro F1: 39.83
macro precision: 36.87
macro recall: 45.03

The result for Derczynski is:
micro F1: 47.49
micro precision: 39.49
micro recall: 59.56
macro F1: 44.18
macro precision: 44.26
macro recall: 47.3

Maybe there are some problems with my GENRE settings, the functions I used to generate the predictions and etc. I would really appreciate it if you could let me know the mistakes and share some more details.

**Comment by hideaki-j** [comment]
Hello. I am also still struggling to reproduce your results. 

Since my results are very different from the reported results, I understand that the settings mentioned in #30 have a large impact on the performance of the tool.
(The result which I obtained using KORE50 was 0.3521 (InKB Micro F1), while the result reported in the paper was 60.7.)

> In particular, I used the entity universe from https://github.com/dalab/end2end_neural_el and the same from the mapping from mention to candidates. I also did some filtering (e.g., since the task is named entity linking and not entity linking in general, I removed all mentions that do not start with a capital letter). (from #30)

Specifically, I would like to know:

1. Where can I find "entity_univers" in the repo you specified. And how did you use it in your code?
2. What does "the same from the mapping from mention to candidates" specifically mean?
3. What is the detailed procedure to perform "some filtering" (Could you share the code which you used for filtering?)

It would be appreciated if you share your evaluation code including additional changes that affect the results.

**Comment by nicola-decao** [comment]
@Wenyueh  In https://github.com/dalab/end2end_neural_el there is a link to download the data. In the data you will find `entities_universe.txt` and `prob_yago_crosswikis_wikipedia_p_e_m.txt` . The fist contains all the entities used as KB. Therefore in GENRE you can use these for building a Trie and give it to the generation function as `candidates_trie`. This basically reduces the number of entities from all possible English strings that the model would generate to only ~500k.

I also used the second file to generate `mention_to_candidates_dict` and `mention_trie`. In that file there is a mapping between mentions and entities that is used for generating the mention to candidates python dictionary and I built a Trie with all mentions for the `mention_trie`. With those 2 parameters you don’t need `candidates_trie` as it is implicit in `mention_to_candidates_dict`. This lead to the best performance.

**Comment by nicola-decao** [comment]
@Wenyueh I developed GENRE during an internship so to answer your points: No, I don't have that code nor the data anymore sorry.

**Comment by nicola-decao** [comment]
@hideaki-j See my points below. In addition to that "mapping from mention to candidates" is a table mention -> list of candidates that is used instead of letting the model to freely generate any entity from the KB. This reduces the set of choices to a few and has a much higher recall. The ` prob_yago_crosswikis_wikipedia_p_e_m.txt` contains that mapping.

With "some filtering" I mean that I excluded mentions that started with a lowercase letter. I probably removed all mentions that contained non-English character and that started with puntuaction.

**Comment by Chiaoso** [comment]
> @hideaki-j See my points below. In addition to that "mapping from mention to candidates" is a table mention -> list of candidates that is used instead of letting the model to freely generate any entity from the KB. This reduces the set of choices to a few and has a much higher recall. The ` prob_yago_crosswikis_wikipedia_p_e_m.txt` contains that mapping.
> 
> With "some filtering" I mean that I excluded mentions that started with a lowercase letter. I probably removed all mentions that contained non-English character and that started with puntuaction.

Could you explain how to generate the map with prob_yago_crosswikis_wikipedia_p_e_m.txt? I cannot understand its format.
